### ISSUE TITLE
Self-loop needed to draw HMM diagram.

### ISSUE THREAD

**Issue by gundalav** [daft-dev/daft#71] opened 2014-07-12 14:28 UTC
Daft is a great tool! 
Please make the self-loop available:

http://stackoverflow.com/questions/24713691/adding-self-edge-in-a-graphical-plot-with-pythons-daft-library/24713830#24713830

**Comment by dsfulf** [comment] 2019-09-04 22:44
Duplicate of #61.

**Closed by dsfulf** 2019-09-04 22:44 UTC
